### PR TITLE
Add dashboard Components.

### PR DESCRIPTION
**Pull request by karloscarweber**
I'm building out the dashboard designs into reusable components, and documenting them as I go along. The goal is to get coverage for most of the designs and have each layout browser and responsive tested.

Also expect improvements to the documentation styles as I've mildly redesigned it and have changes.

### CODE REVIEW

**Comment by karloscarweber** [comment]
I'm decoupling _stock-photo from the style guide build sequence because it relies on a jekyll plugin to get the images to load properly. These images are also only used in the `www-static` site and not in the `website` repo at all. This tells me that the stock images are almost exclusively for editorial content. 

Next step is to make sure that _stock-photo is included in a new build sequence for `www-static` that inherits from `styleguide`.

**Comment by orangejulius** [comment]
Yeah, the way we render those stock photos always confused me. My understanding is that there's some advantage to using CSS to specify the image via the `background` property, but it means we have to put all the image filenames in CSS which seems hard to reuse. I think part of the point of the styleguide is to improve stuff like this :)

**Comment by karloscarweber** [comment]
> Yeah, the way we render those stock photos always confused me. My understanding is that there's some advantage to using CSS to specify the image via the `background` property, but it means we have to put all the image filenames in CSS which seems hard to reuse. I think part of the point of the styleguide is to improve stuff like this :)

Right! Step one is to decouple. Step to is to only add these to `www-static`. The only place they are used. I'm not averse to rethinking this particular issue, seeing if there is a better way, But maybe down the road after we've got most of the dashboard UI Built and ready.

**Comment by karloscarweber** [comment]
A major blocker i'm experiencing right now is with the overflow in the documentation at mid-sizes. I've narrowed down to the code elements that we're using, that, sometimes, causes the column to grow improperly.

This only happens at mid sizes and seems to be related to the flexbox columns and how they calculate their internal width. I'm trying to resolve it.

**Comment by karloscarweber** [comment]
I’ve overhauled the sidebar in the documentation. I'm baking it into this PR, so it will land when this is merged.

**Comment by orangejulius** [comment]
Just checked out the new docs sidebar . Looks very nice :)
Screenshot_2020-06-01_07-49-43

**Pull request merged**
